name: "tatya dan ilmin"

services:
  nginx:
    image: nginx:latest  
    container_name: nginx-service
    ports:
      - "8080:80"  
    volumes:
      - nginx_conf:/etc/nginx/
      - html:/usr/share/nginx/html 
      - .:/app
    networks:
      - app_network
    depends_on:
      - webapp
    restart: always

  webapp:
    container_name: webapp
    build:
      context: ./app  
      dockerfile: Dockerfile 
    image: learning-hub:latest
    ports:
      - "8000:8000" 
    volumes:
      - ./app:/app 
    environment:
      - PYTHONUNBUFFERED=1 
    networks:
      - app_network
    restart: always 
    depends_on:
      - db 

  db:
    image: postgres:latest  
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest 
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com  
      PGADMIN_DEFAULT_PASSWORD: adminpassword 
    ports:
      - "8082:80"  
    networks:
      - app_network
    depends_on:
      - db
    restart: always

networks:
  app_network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  nginx_conf:
    driver: local
  html:
    driver: local

configs:
  nginx_config:
    file: ./nginx.conf